[tool.poetry]
name = "expenses"
version = "0.1.0"
description = "Solo project"
authors = ["Artur"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
django = "^5.1.1"
datetime = "^5.5"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
